theme: jekyll-theme-minimal
title: 'Bulk RNA-Seq Analysis'
show_downloads: True
navigation:
  - title: Home
    url: /

  - heading: Discussion and Lectures
  - title: Intro to the Workshop
    url: base/welcome
  - title: What is Bioinformatics/Genomics?
    url: pdfs/Genomics_a_perspective_Aug_2024.pdf
  - title: Experimental Design and Cost Estimation
    url: pdfs/scRNAseq-expDesign_Aug_2024.pdf
  - title: Closing thoughts
    url: base/closing

  - heading: Data Reduction
  - title: Files and Filetypes
    url: data_reduction/filetypes
  - title: Generating Expression Matrix
    url: data_reduction/Expression_Matrix


  - heading: Data analysis
  - title: Prepare scRNAseq Analysis
    url: data_analysis/00-prepare
  # - title: Part 1- Create object
  #   url: data_analysis/01-create_object
  # - title: Part 2- Filtering
  #   url: data_analysis/02-filtering
  # - title: Part 3- Normalization and scaling
  #   url: data_analysis/03-normalize_scale
  # - title: Part 4- Dimensionality reduction
  #   url: data_analysis/04-dimensionality_reduction
  # - title: Part 5- Clustering and cell type
  #   url: data_analysis/05-clustering_celltype
  # - title: Part 6- Enrichment and DE
  #   url: data_analysis/06-de_enrichment
  # - title: Part 7- Doublet detection
  #   url: data_analysis/07-doublet_detection
  # - title: Part 8- Integration
  #   url: data_analysis/08-integration

  - heading: Prerequisites
  - title: CLI
    url: base/cli_prerequisites
  - title: R
    url: base/r_prerequisites

  - heading: Support
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: ETC
  - title: CAT website
    url: https://cat.ucsf.edu/
  - title: Github page
    url: https://github.com/UCSF-CAT-Bioinformatics/2024-08-SCRNA-Seq-Analysis
  - title: Report Errors
    url: https://github.com/UCSF-CAT-Bioinformatics/2024-08-SCRNA-Seq-Analysis/issues
